nanexcool/daistats

src/App.jsx, src/Main.jsx
I was interested how much a MKR holder would receive as a compensation for the insurance risk.
The displayed ROI number is basically how much profit a MKR holder can expect in one year for a given USD investment -- IF the dai supply and stability fee remains stable for a year.
It currently says 0.94 %.
If there is a logical or economic error in this PR, I'm happy to discuss it.
It is also totally fine if you reject this PR in case you don't want this number in the dashboard.
=> Add MKR return on investment

public/index.html
Hey @nanexcool, thought this might be appropriate. If you don't think so, just close the PR— I won't be offended ;) Cheers!
> usedai.org is a redirect to an "Awesome List" style GitHub project.
> Community members can open a pull request to add their business,
> consultancy, or DApp to a growing list of places where you can USE
> DAI.
=> Add usedai.org to the footer

src/App.jsx, src/Main.jsx
adding the last drip on Pot and re-arranging Uniswap
=> Add pot drip

public/index.html, src/Main.jsx
* Adds a fontawesome pro import (enabled for daistats.com)
* Adds info + etherscan links for Dai, Sai, and MKR
=> Add Token contract addresses

src/Main.jsx
It was pointed out that the SAI rate being 0% was confusing with the SCD SF fee.  Adding a link and info to clarify
=> add message and link clarifying the SAI Stability Fee

README.md
you need to `npm install` after cloning
=> tiny change to make it work :D

src/App.jsx, src/Main.jsx
Ratio shown is around 2% less then whats shown on https://oasis.app/borrow/
Would be better to use BigNumber for the whole `sysCollat` calculation, division is done with Number type atm.
Don't understand why `formatUnits(x, 36)` is done but it gives the correct result.
=> Show system Collat. Ratio and Total Locked collateral

package-lock.json, package.json, src/App.jsx, src/HealButton.js, src/Main.jsx
Adds a "Heal" button to https://daistats.com/ that anyone can use to `heal` the system debt.
**TODO:**
=> add System Debt HealButton

src/HealButton.jsx, src/Main.jsx
That shiny white button hurts my eyes.
=> Make heal button dark in dark mode

src/HealButton.jsx
Removes error due to duplicate titles
=> Remove duplicate title

package-lock.json, package.json, src/App.jsx, src/Main.jsx
Daistats doesn't load if metamask is present and not on mainnet. This fixes it to use the default ethers provider when some other network is present.
Also npm updates a couple of dependencies.
=> Fix for non-mainnet metamask setup

src/Main.jsx
Add Surplus buffer lot size to sub-title
=> show the flap bump - surplus buffer lot size

src/App.jsx, src/Main.jsx, yarn.lock
I noticed that the calculation to the next flap seemed rather large.
I believe this is because the calculation double counted the `sin`.  The current surplus calculation already subtracts the `sin` but the flap calc was adding it in to the amount needed before a flap was kicked off.  (@nanexcool can you double check my math here)
I also reformatted so the calculation happens in a helper function rather than inline with the jsx.
=> Fix next flap calc

src/App.jsx
Adds WBTC and USDC collateral to MKR burn calculation.
=> Add WBTC and USDC to MKR burn rate

src/App.jsx
Usually masculine in this context
=> Français instead of Française

package.json, src/App.jsx
Don't merge this PR until defi18n 0.0.8 is released including Irish :)
=> WIP: Add irish once defi18n package updated

src/App.jsx, src/Main.jsx
Please check usdc-b and tusd fee and Ceiling values,
=> Add USDC-B and TUSD ilks

src/App.jsx, src/Main.jsx
Removed old index comments, noted unused vars.
Use Bulma css classes to colour OSM next prices.
=> Colour next price

src/App.jsx, src/Main.jsx
- adds PAX-A
- adds USDT-A
- fix MANA-A missing bits
NOTE PIP_PAX (DSValue) and PIP_USDT (OSM) addresses missing, need to add these at the top of `App.jsx` when known.
=> Add PAX-A and USDT-A ilks

public/index.html
Follow-up to https://github.com/nanexcool/daistats/pull/123
=> Remove unecessary code
